# Generated by Django 5.1.1 on 2024-10-14 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacion','0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categoria', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_estado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_prioridad', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_servicio', models.CharField(max_length=20)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('comentario_resolucion', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.categoria')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.estado')),
                ('prioridad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.prioridad')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='FechaTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_fecha', models.CharField(choices=[('Creacion', 'Creación'), ('Cierre', 'Cierre')], max_length=20)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
            ],
            options={
                'unique_together': {('fecha', 'ticket')},
            },
        ),
        migrations.CreateModel(
            name='DetalleUsuarioTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacion_ticket', models.CharField(choices=[('creador', 'Creador'), ('asignado', 'Asignado'), ('resuelto', 'Resuelto')], max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
            ],
            options={
                'unique_together': {('ticket', 'usuario', 'relacion_ticket')},
            },
        ),
    ]
