# Generated by Django 5.1.1 on 2024-10-22 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='comentario_resolucion',
            new_name='comentario',
        ),
    ]
