# Generated by Django 5.1.1 on 2024-11-10 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_ticket_user_ticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sla_status',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='fechaticket',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fechaticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechaticket_set', to='tickets.ticket'),
        ),
        migrations.AlterField(
            model_name='fechaticket',
            name='tipo_fecha',
            field=models.CharField(choices=[('Creacion', 'Creación'), ('cierre_esperado', 'cierre_esperado'), ('Cierre', 'Cierre')], max_length=40),
        ),
    ]
