# Generated by Django 5.1.1 on 2024-11-12 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_sla_status_alter_fechaticket_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='sla_status',
            field=models.CharField(blank=True, default='On Track', max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='PresupuestoTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presupuesto_mensual', models.DecimalField(decimal_places=2, default=1000000, help_text='Monthly budget for the department', max_digits=12)),
                ('presupuesto_gastado', models.DecimalField(decimal_places=2, default=0, help_text='Amount spent for the month', max_digits=12)),
                ('presupuesto_restante', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('over_budget', models.BooleanField(blank=True, default=False, null=True)),
                ('fecha_presupuesto', models.DateField(help_text='Month for this budget record')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('fecha_presupuesto__month', models.F('fecha_presupuesto__month')), ('fecha_presupuesto__year', models.F('fecha_presupuesto__year'))), fields=('fecha_presupuesto',), name='unique_monthly_presupuesto')],
            },
        ),
        migrations.CreateModel(
            name='Costo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('calculo_monto', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True)),
                ('monto_final', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos', to='tickets.ticket')),
                ('presupuesto_ti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos', to='tickets.presupuestoti')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ticket', 'presupuesto_ti'), name='unique_costo_ticket_presupuesto')],
                'unique_together': {('ticket', 'presupuesto_ti')},
            },
        ),
    ]
