# Generated by Django 5.1.1 on 2024-11-18 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_ticket_sla_status_presupuestoti_costo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costo',
            name='calculo_monto',
        ),
        migrations.AddField(
            model_name='costo',
            name='cierre',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='costo',
            name='horas_atraso',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costo',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='costos', to='tickets.ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sla_status',
            field=models.CharField(blank=True, default='Al dia', max_length=40, null=True),
        ),
    ]
