# Generated by Django 5.1.1 on 2024-11-26 19:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_categoria_sla_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolucion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EvaluacionTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField(help_text='Calificación del ticket (1: Muy malo, 5: Excelente)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback', models.TextField(blank=True, help_text='Comentarios opcionales', null=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion', to='tickets.ticket')),
            ],
        ),
    ]
